ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER APP IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT EXECUTE ON AUDITORIA.PROC_AUDITORIA TO APP;
GRANT INSERT ON AUDITORIA.AUDITORIA TO APP;
GRANT CONNECT, RESOURCE TO APP;

-- Trigger para auditoria da tabela H_VOO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_VOO"
AFTER UPDATE OR DELETE ON H_VOO
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'H_VOO';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,NULL,NULL,NULL,V_USU_BD,V_USU_SO,SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        
        IF (:NEW.H_VOO_ID <> :OLD.H_VOO_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_ID',:OLD.H_VOO_ID,:NEW.H_VOO_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_NUMERO <> :OLD.H_VOO_NUMERO) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_NUMERO',:OLD.H_VOO_NUMERO,:NEW.H_VOO_NUMERO,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_EMP_ID <> :OLD.H_VOO_EMP_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_EMP_ID',:OLD.H_VOO_EMP_ID,:NEW.H_VOO_EMP_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_COD_DI <> :OLD.H_VOO_COD_DI) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_COD_DI',:OLD.H_VOO_COD_DI,:NEW.H_VOO_COD_DI,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_COD_TIPO_LINHA <> :OLD.H_VOO_COD_TIPO_LINHA) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_COD_TIPO_LINHA',:OLD.H_VOO_COD_TIPO_LINHA,:NEW.H_VOO_COD_TIPO_LINHA,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_MOD_EQUIP <> :OLD.H_VOO_MOD_EQUIP) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_MOD_EQUIP',:OLD.H_VOO_MOD_EQUIP,:NEW.H_VOO_MOD_EQUIP,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_NUM_ASSENTOS <> :OLD.H_VOO_NUM_ASSENTOS) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_NUM_ASSENTOS',:OLD.H_VOO_NUM_ASSENTOS,:NEW.H_VOO_NUM_ASSENTOS,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_AER_ORI_ID <> :OLD.H_VOO_AER_ORI_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_AER_ORI_ID',:OLD.H_VOO_AER_ORI_ID,:NEW.H_VOO_AER_ORI_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_AER_DES_ID <> :OLD.H_VOO_AER_DES_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_AER_DES_ID',:OLD.H_VOO_AER_DES_ID,:NEW.H_VOO_AER_DES_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_STS_PART_ID <> :OLD.H_VOO_STS_PART_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_STS_PART_ID',:OLD.H_VOO_STS_PART_ID,:NEW.H_VOO_STS_PART_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_STS_CHEG_ID <> :OLD.H_VOO_STS_CHEG_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_STS_CHEG_ID',:OLD.H_VOO_STS_CHEG_ID,:NEW.H_VOO_STS_CHEG_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_VOO_DATA_ALTERACAO <> :OLD.H_VOO_DATA_ALTERACAO) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_VOO_DATA_ALTERACAO',TO_CHAR(:OLD.H_VOO_DATA_ALTERACAO,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_VOO_DATA_ALTERACAO,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_VOO" ENABLE;

-- Trigger para auditoria da tabela H_DATAS_VOO
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_DATAS_VOO"
AFTER UPDATE OR DELETE ON H_DATAS_VOO
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'H_DATAS_VOO';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,NULL,NULL,NULL,V_USU_BD,V_USU_SO,SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        
        IF (:NEW.H_DTV_ID <> :OLD.H_DTV_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_ID',:OLD.H_DTV_ID,:NEW.H_DTV_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_VOO_ID <> :OLD.H_DTV_VOO_ID) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_VOO_ID',:OLD.H_DTV_VOO_ID,:NEW.H_DTV_VOO_ID,V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_PART_PREV <> :OLD.H_DTV_PART_PREV) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_PART_PREV',TO_CHAR(:OLD.H_DTV_PART_PREV,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_DTV_PART_PREV,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_PART_REAL <> :OLD.H_DTV_PART_REAL) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_PART_REAL',TO_CHAR(:OLD.H_DTV_PART_REAL,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_DTV_PART_REAL,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_CHEG_PREV <> :OLD.H_DTV_CHEG_PREV) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_CHEG_PREV',TO_CHAR(:OLD.H_DTV_CHEG_PREV,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_DTV_CHEG_PREV,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_CHEG_REAL <> :OLD.H_DTV_CHEG_REAL) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_CHEG_REAL',TO_CHAR(:OLD.H_DTV_CHEG_REAL,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_DTV_CHEG_REAL,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_REF <> :OLD.H_DTV_REF) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_REF',TO_CHAR(:OLD.H_DTV_REF,'DD/MM/YYYY'),TO_CHAR(:NEW.H_DTV_REF,'DD/MM/YYYY'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
        
        IF (:NEW.H_DTV_DATA_ALTERACAO <> :OLD.H_DTV_DATA_ALTERACAO) THEN
            PROC_AUDITORIA(V_TABELA,V_ROWID,V_TP_OPERACAO,'H_DTV_DATA_ALTERACAO',TO_CHAR(:OLD.H_DTV_DATA_ALTERACAO,'DD/MM/YYYY HH24:MI:SS'),TO_CHAR(:NEW.H_DTV_DATA_ALTERACAO,'DD/MM/YYYY HH24:MI:SS'),V_USU_BD,V_USU_SO,SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_DATAS_VOO" ENABLE;

