-- SEQUENCES
CREATE SEQUENCE SEQ_VOO MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_EMPRESA MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_STATUS MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DATAS_VOO MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_COMPANHIA MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AEROPORTO MINVALUE 1 INCREMENT BY 1 START WITH 1;

-- TABLES
-- COMPANHIA_AEREA
CREATE TABLE COMPANHIA_AEREA (
    COM_ID NUMBER PRIMARY KEY,
    COM_NOME VARCHAR2(255) UNIQUE
);

COMMENT ON TABLE COMPANHIA_AEREA IS 'Armazena os dados das companhias aéreas, que são as holding companies do setor';
COMMENT ON COLUMN COMPANHIA_AEREA.COM_ID IS 'Identificador único da companhia aérea (PK)';
COMMENT ON COLUMN COMPANHIA_AEREA.COM_NOME IS 'Nome completo da companhia aérea (ex: LATAM Airlines Group)';

-- EMPRESA_AEREA
CREATE TABLE EMPRESA_AEREA (
    EMP_ID NUMBER PRIMARY KEY,
    EMP_SIGLA_ICAO VARCHAR2(10) UNIQUE,
    EMP_COM_ID NUMBER,
    FOREIGN KEY (EMP_COM_ID) REFERENCES COMPANHIA_AEREA(COM_ID)
);

COMMENT ON TABLE EMPRESA_AEREA IS 'Registra as empresas aéreas operadoras, que são subsidiárias das companhias';
COMMENT ON COLUMN EMPRESA_AEREA.EMP_ID IS 'Identificador único da empresa aérea (PK)';
COMMENT ON COLUMN EMPRESA_AEREA.EMP_SIGLA_ICAO IS 'Código ICAO único da empresa (ex: TAM para LATAM Brasil)';
COMMENT ON COLUMN EMPRESA_AEREA.EMP_COM_ID IS 'Referência à companhia controladora (FK para COMPANHIA_AEREA)';

-- AEROPORTO
CREATE TABLE AEROPORTO (
    AER_ID NUMBER PRIMARY KEY,
    AER_SIGLA VARCHAR2(4) NOT NULL,
    AER_NOME VARCHAR2(255) NOT NULL,
    AER_EMP_ID NUMBER,
    FOREIGN KEY (AER_EMP_ID) REFERENCES EMPRESA_AEREA(EMP_ID)
); 

COMMENT ON TABLE AEROPORTO IS 'Cadastro de aeroportos com informações básicas de identificação';
COMMENT ON COLUMN AEROPORTO.AER_ID IS 'Identificador único do aeroporto (PK)';
COMMENT ON COLUMN AEROPORTO.AER_SIGLA IS 'Código IATA do aeroporto (ex: GRU para Guarulhos)';
COMMENT ON COLUMN AEROPORTO.AER_NOME IS 'Nome oficial do aeroporto';
COMMENT ON COLUMN AEROPORTO.AER_EMP_ID IS 'Referência à empresa aérea principal associada (FK para EMPRESA_AEREA)';

-- STATUS_VOO
CREATE TABLE STATUS_VOO (
    STS_ID NUMBER PRIMARY KEY,
    STS_TIPO VARCHAR2(10) CHECK (STS_TIPO IN ('PARTIDA', 'CHEGADA')),
    STS_DESC VARCHAR2(50) NOT NULL,
    CONSTRAINT UK_STATUS UNIQUE (STS_TIPO, STS_DESC)
);

COMMENT ON TABLE STATUS_VOO IS 'Define os possíveis status de partida e chegada de voos';
COMMENT ON COLUMN STATUS_VOO.STS_ID IS 'Identificador único do status (PK)';
COMMENT ON COLUMN STATUS_VOO.STS_TIPO IS 'Tipo do status (PARTIDA ou CHEGADA)';
COMMENT ON COLUMN STATUS_VOO.STS_DESC IS 'Descrição do status (ex: Programado, Embarcando, Taxiando)';

-- VOO
CREATE TABLE VOO (
    VOO_ID NUMBER PRIMARY KEY,
    VOO_NUMERO VARCHAR2(10),
    VOO_EMP_ID NUMBER,
    VOO_COD_DI VARCHAR2(10),
    VOO_COD_TIPO_LINHA VARCHAR2(10),
    VOO_MOD_EQUIP VARCHAR2(50),
    VOO_NUM_ASSENTOS NUMBER,
    VOO_AER_ORI_ID NUMBER,
    VOO_AER_DES_ID NUMBER,
    VOO_STS_PART_ID NUMBER,
    VOO_STS_CHEG_ID NUMBER,
    FOREIGN KEY (VOO_EMP_ID) REFERENCES EMPRESA_AEREA(EMP_ID),
    FOREIGN KEY (VOO_AER_ORI_ID) REFERENCES AEROPORTO(AER_ID),
    FOREIGN KEY (VOO_AER_DES_ID) REFERENCES AEROPORTO(AER_ID),
    FOREIGN KEY (VOO_STS_PART_ID) REFERENCES STATUS_VOO(STS_ID),
    FOREIGN KEY (VOO_STS_CHEG_ID) REFERENCES STATUS_VOO(STS_ID)
);

COMMENT ON TABLE VOO IS 'Registro completo de todos os voos operados pelo sistema';
COMMENT ON COLUMN VOO.VOO_ID IS 'Identificador único do voo (PK)';
COMMENT ON COLUMN VOO.VOO_NUMERO IS 'Número do voo conforme definido pela empresa (ex: LA 1234)';
COMMENT ON COLUMN VOO.VOO_EMP_ID IS 'Empresa aérea operadora do voo (FK para EMPRESA_AEREA)';
COMMENT ON COLUMN VOO.VOO_COD_DI IS 'Código de identificação do voo (DI)';
COMMENT ON COLUMN VOO.VOO_COD_TIPO_LINHA IS 'Tipo de linha aérea (Doméstica, Internacional, etc)';
COMMENT ON COLUMN VOO.VOO_MOD_EQUIP IS 'Modelo da aeronave utilizada no voo';
COMMENT ON COLUMN VOO.VOO_NUM_ASSENTOS IS 'Capacidade total de passageiros da aeronave';
COMMENT ON COLUMN VOO.VOO_AER_ORI_ID IS 'Aeroporto de origem do voo (FK para AEROPORTO)';
COMMENT ON COLUMN VOO.VOO_AER_DES_ID IS 'Aeroporto de destino do voo (FK para AEROPORTO)';
COMMENT ON COLUMN VOO.VOO_STS_PART_ID IS 'Status atual da partida (FK para STATUS_VOO)';
COMMENT ON COLUMN VOO.VOO_STS_CHEG_ID IS 'Status atual da chegada (FK para STATUS_VOO)';

-- DATAS_VOO
CREATE TABLE DATAS_VOO (
    DTV_ID NUMBER PRIMARY KEY,
    DTV_VOO_ID NUMBER,
    DTV_PART_PREV TIMESTAMP,
    DTV_PART_REAL TIMESTAMP,
    DTV_CHEG_PREV TIMESTAMP,
    DTV_CHEG_REAL TIMESTAMP,
    DTV_REF DATE,
    FOREIGN KEY (DTV_VOO_ID) REFERENCES VOO(VOO_ID)
);

COMMENT ON TABLE DATAS_VOO IS 'Registra os horários previstos e reais de partida/chegada dos voos';
COMMENT ON COLUMN DATAS_VOO.DTV_ID IS 'Identificador único do registro de data/horário (PK)';
COMMENT ON COLUMN DATAS_VOO.DTV_VOO_ID IS 'Referência ao voo relacionado (FK para VOO)';
COMMENT ON COLUMN DATAS_VOO.DTV_PART_PREV IS 'Data e hora previstas para partida';
COMMENT ON COLUMN DATAS_VOO.DTV_PART_REAL IS 'Data e hora reais da partida';
COMMENT ON COLUMN DATAS_VOO.DTV_CHEG_PREV IS 'Data e hora previstas para chegada';
COMMENT ON COLUMN DATAS_VOO.DTV_CHEG_REAL IS 'Data e hora reais da chegada';
COMMENT ON COLUMN DATAS_VOO.DTV_REF IS 'Data de referência para agrupamento de voos';

-- TRIGGERS
CREATE OR REPLACE TRIGGER TRG_COMPANHIA_AI
BEFORE INSERT ON COMPANHIA_AEREA
FOR EACH ROW
BEGIN
    :NEW.COM_ID := SEQ_COMPANHIA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMPRESA_ID
BEFORE INSERT ON EMPRESA_AEREA
FOR EACH ROW
BEGIN
    :NEW.EMP_ID := SEQ_EMPRESA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_AEROPORTO_AI
BEFORE INSERT ON AEROPORTO
FOR EACH ROW
BEGIN
   :NEW.AER_ID := SEQ_AEROPORTO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DATAS_VOO_AI
BEFORE INSERT ON DATAS_VOO
FOR EACH ROW
BEGIN
    :NEW.DTV_ID := SEQ_DATAS_VOO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_VOO_AI
BEFORE INSERT ON VOO
FOR EACH ROW
BEGIN
    :NEW.VOO_ID := SEQ_VOO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_STATUS_AI
BEFORE INSERT ON STATUS_VOO
FOR EACH ROW
BEGIN
    :NEW.STS_ID := SEQ_STATUS.NEXTVAL;
END;
/

-- INSERTS (atualizados com os novos nomes de colunas)
INSERT INTO COMPANHIA_AEREA(COM_NOME)
SELECT DISTINCT EMPRESA 
FROM VRA_11;

INSERT INTO EMPRESA_AEREA (EMP_SIGLA_ICAO, EMP_COM_ID)
SELECT v.ICAO, c.COM_ID
FROM (
    SELECT ICAO, empresa, 
           ROW_NUMBER() OVER (PARTITION BY ICAO ORDER BY empresa) AS rn
    FROM VRA_11 
    WHERE ICAO IS NOT NULL
) v
JOIN COMPANHIA_AEREA c ON v.empresa = c.COM_NOME
WHERE v.rn = 1
AND NOT EXISTS (
    SELECT 1 FROM EMPRESA_AEREA ea 
    WHERE ea.EMP_SIGLA_ICAO = v.ICAO
);

INSERT INTO AEROPORTO (AER_SIGLA, AER_NOME, AER_EMP_ID)
SELECT 
    v.AER_ORIGEM,
    v.DESC_AER_ORIG,  
    e.EMP_ID
FROM 
    (SELECT DISTINCT AER_ORIGEM, DESC_AER_ORIG, ICAO FROM VRA_11) v
    JOIN EMPRESA_AEREA e ON v.ICAO = e.EMP_SIGLA_ICAO
UNION
SELECT 
    v.AER_DEST,
    v.DESC_AER_DEST,  
    e.EMP_ID
FROM 
    (SELECT DISTINCT AER_DEST, DESC_AER_DEST, ICAO FROM VRA_11) v
    JOIN EMPRESA_AEREA e ON v.ICAO = e.EMP_SIGLA_ICAO;
 
INSERT INTO STATUS_VOO (STS_TIPO, STS_DESC)
SELECT 'PARTIDA', v.SITUA_PART
FROM (SELECT DISTINCT SITUA_PART FROM VRA_11 WHERE SITUA_PART IS NOT NULL) v;

INSERT INTO STATUS_VOO (STS_TIPO, STS_DESC)
SELECT 'CHEGADA', v.SITUA_CHEG
FROM (SELECT DISTINCT SITUA_CHEG FROM VRA_11 WHERE SITUA_CHEG IS NOT NULL) v;

INSERT INTO VOO (
    VOO_NUMERO,
    VOO_EMP_ID,
    VOO_COD_DI,
    VOO_COD_TIPO_LINHA,
    VOO_MOD_EQUIP,
    VOO_NUM_ASSENTOS,
    VOO_AER_ORI_ID,
    VOO_AER_DES_ID,
    VOO_STS_PART_ID,
    VOO_STS_CHEG_ID
)
WITH 
vra_distinct AS (
    SELECT DISTINCT 
        NÚM,
        ICAO,
        DI,
        LINHA,
        MODELO,
        ASSENTOS,
        AER_ORIGEM,
        AER_DEST,
        SITUA_PART,
        SITUA_CHEG
    FROM VRA_11
),
empresa_unique AS (
    SELECT 
        EMP_SIGLA_ICAO,
        MIN(EMP_ID) AS EMP_ID 
    FROM EMPRESA_AEREA
    GROUP BY EMP_SIGLA_ICAO
),
aeroporto_unique AS (
    SELECT 
        AER_SIGLA,
        MIN(AER_ID) AS AER_ID
    FROM AEROPORTO
    GROUP BY AER_SIGLA
)
SELECT 
    v.NÚM,
    eu.EMP_ID,
    v.DI,
    COALESCE(v.LINHA, 'N/I'),
    COALESCE(v.MODELO, 'MODELO NÃO INFORMADO'),
    COALESCE(v.ASSENTOS, 0),
    (SELECT AER_ID FROM aeroporto_unique WHERE AER_SIGLA = v.AER_ORIGEM),
    (SELECT AER_ID FROM aeroporto_unique WHERE AER_SIGLA = v.AER_DEST),
    (SELECT MIN(STS_ID) FROM STATUS_VOO WHERE STS_TIPO = 'PARTIDA' AND STS_DESC = v.SITUA_PART),
    COALESCE(
        (SELECT MIN(STS_ID) FROM STATUS_VOO WHERE STS_TIPO = 'CHEGADA' AND STS_DESC = v.SITUA_CHEG),
        (SELECT MIN(STS_ID) FROM STATUS_VOO WHERE STS_TIPO = 'CHEGADA' AND STS_DESC = 'STATUS NÃO INFORMADO')
    )
FROM vra_distinct v
LEFT JOIN empresa_unique eu ON eu.EMP_SIGLA_ICAO = v.ICAO;

INSERT INTO DATAS_VOO (
    DTV_PART_PREV,
    DTV_PART_REAL,
    DTV_CHEG_PREV,
    DTV_CHEG_REAL,
    DTV_REF,
    DTV_VOO_ID
)
SELECT 
    v.PART_PREV,
    v.PART_REAL,
    v.CHEG_PREV,
    v.CHEG_REAL,
    v.REFERÊNCIA,
    vo.VOO_ID
FROM (
    SELECT DISTINCT
        NÚM,
        PART_PREV,
        PART_REAL,
        CHEG_PREV,
        CHEG_REAL,
        REFERÊNCIA
    FROM VRA_11
) v
JOIN VOO vo ON v.NÚM = vo.VOO_NUMERO;

-- CONSULTAS ESTRATÉGICAS (atualizadas com os novos nomes de colunas)
-- Rotas mais populares (maior número de voos)
SELECT 
    ao.AER_SIGLA AS ORIGEM,
    ao.AER_NOME AS NOME_ORIGEM,
    ad.AER_SIGLA AS DESTINO,
    ad.AER_NOME AS NOME_DESTINO,
    COUNT(*) AS TOTAL_VOOS
FROM 
    VOO v
JOIN AEROPORTO ao ON v.VOO_AER_ORI_ID = ao.AER_ID
JOIN AEROPORTO ad ON v.VOO_AER_DES_ID = ad.AER_ID
GROUP BY 
    ao.AER_SIGLA, ao.AER_NOME, ad.AER_SIGLA, ad.AER_NOME
ORDER BY 
    TOTAL_VOOS DESC
FETCH FIRST 10 ROWS ONLY;

-- Aeroportos com maior número de voos de saída
SELECT 
    a.AER_SIGLA AS AEROPORTO,
    a.AER_NOME AS NOME_AEROPORTO,
    COUNT(*) AS TOTAL_VOOS_SAIDA
FROM 
    VOO v
JOIN AEROPORTO a ON v.VOO_AER_ORI_ID = a.AER_ID
GROUP BY 
    a.AER_SIGLA, a.AER_NOME
ORDER BY 
    TOTAL_VOOS_SAIDA DESC
FETCH FIRST 10 ROWS ONLY;

-- Modelos de aeronaves mais utilizados
SELECT 
    VOO_MOD_EQUIP,
    COUNT(*) AS TOTAL_VOOS
FROM 
    VOO
WHERE 
    VOO_MOD_EQUIP != 'MODELO NÃO INFORMADO'
GROUP BY 
    VOO_MOD_EQUIP
ORDER BY 
    TOTAL_VOOS DESC;

-- Voos por dia da semana   
SELECT 
    TO_CHAR(dv.DTV_REF, 'DAY') AS DIA_SEMANA,
    COUNT(*) AS TOTAL_VOOS
FROM 
    DATAS_VOO dv
GROUP BY 
    TO_CHAR(dv.DTV_REF, 'DAY'), TO_CHAR(dv.DTV_REF, 'D')
ORDER BY 
    TO_CHAR(dv.DTV_REF, 'D');
    
-- Companhias aéreas com maior diversidade de rotas
SELECT 
    c.COM_NOME AS COMPANHIA_AEREA,
    COUNT(DISTINCT v.VOO_AER_ORI_ID || '-' || v.VOO_AER_DES_ID) AS ROTAS_DISTINTAS
FROM 
    VOO v
JOIN EMPRESA_AEREA ea ON v.VOO_EMP_ID = ea.EMP_ID
JOIN COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
GROUP BY 
    c.COM_NOME
ORDER BY 
    ROTAS_DISTINTAS DESC;
    
-- Companhias com Melhor Pontualidade
SELECT 
    c.COM_NOME AS COMPANHIA_AEREA,
    COUNT(*) AS TOTAL_VOOS,
    SUM(CASE WHEN sv.STS_DESC = 'Pontual' AND sv.STS_TIPO = 'PARTIDA' THEN 1 ELSE 0 END) AS VOOS_PONTUAIS,
    ROUND(SUM(CASE WHEN sv.STS_DESC = 'Pontual' AND sv.STS_TIPO = 'PARTIDA' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS PERCENTUAL_PONTUALIDADE
FROM 
    VOO v
JOIN EMPRESA_AEREA ea ON v.VOO_EMP_ID = ea.EMP_ID
JOIN COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
JOIN STATUS_VOO sv ON v.VOO_STS_PART_ID = sv.STS_ID
GROUP BY 
    c.COM_NOME
ORDER BY 
    PERCENTUAL_PONTUALIDADE DESC;

