--SEQUENCES
CREATE SEQUENCE SEQ_VOO MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_EMPRESA MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_STATUS MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DATAS_VOO MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_COMPANHIA MINVALUE 1 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AEROPORTO MINVALUE 1 INCREMENT BY 1 START WITH 1;

--TABLES
-- COMPANHIA_AEREA: Tabela que armazena informações das companhias aéreas
COMMENT ON TABLE COMPANHIA_AEREA IS 'Armazena os dados das companhias aéreas, que são as holding companies do setor';

COMMENT ON COLUMN COMPANHIA_AEREA.ID_COMPANHIA IS 'Identificador único da companhia aérea (PK)';
COMMENT ON COLUMN COMPANHIA_AEREA.NOME IS 'Nome completo da companhia aérea (ex: LATAM Airlines Group)';

CREATE TABLE COMPANHIA_AEREA (
    ID_COMPANHIA NUMBER PRIMARY KEY,
    NOME VARCHAR2(255) UNIQUE
);


-- EMPRESA_AEREA: Tabela que armazena as empresas operadoras (subsidiárias)
COMMENT ON TABLE EMPRESA_AEREA IS 'Registra as empresas aéreas operadoras, que são subsidiárias das companhias';

COMMENT ON COLUMN EMPRESA_AEREA.ID_EMPRESA IS 'Identificador único da empresa aérea (PK)';
COMMENT ON COLUMN EMPRESA_AEREA.SIGLA_ICAO IS 'Código ICAO único da empresa (ex: TAM para LATAM Brasil)';
COMMENT ON COLUMN EMPRESA_AEREA.ID_COMPANHIA IS 'Referência à companhia controladora (FK para COMPANHIA_AEREA)';

CREATE TABLE EMPRESA_AEREA (
    ID_EMPRESA NUMBER PRIMARY KEY,
    SIGLA_ICAO VARCHAR2(10) UNIQUE,
    ID_COMPANHIA NUMBER,
    FOREIGN KEY (ID_COMPANHIA) REFERENCES COMPANHIA_AEREA(ID_COMPANHIA)
);


-- AEROPORTO: Tabela de aeroportos cadastrados
COMMENT ON TABLE AEROPORTO IS 'Cadastro de aeroportos com informações básicas de identificação';

COMMENT ON COLUMN AEROPORTO.ID_AEROPORTO IS 'Identificador único do aeroporto (PK)';
COMMENT ON COLUMN AEROPORTO.SIGLA_AER IS 'Código IATA do aeroporto (ex: GRU para Guarulhos)';
COMMENT ON COLUMN AEROPORTO.NOME_AEROPORTO IS 'Nome oficial do aeroporto';
COMMENT ON COLUMN AEROPORTO.ID_EMP_AER IS 'Referência à empresa aérea principal associada (FK para EMPRESA_AEREA)';

CREATE TABLE AEROPORTO (
    ID_AEROPORTO NUMBER PRIMARY KEY,
    SIGLA_AER VARCHAR2(4) NOT NULL,
    NOME_AEROPORTO VARCHAR2(255) NOT NULL,
    ID_EMP_AER NUMBER,
    FOREIGN KEY (ID_EMP_AER) REFERENCES EMPRESA_AEREA(ID_EMPRESA)
); 


-- STATUS_VOO: Tabela de status dos voos
COMMENT ON TABLE STATUS_VOO IS 'Define os possíveis status de partida e chegada de voos';

COMMENT ON COLUMN STATUS_VOO.ID_STATUS IS 'Identificador único do status (PK)';
COMMENT ON COLUMN STATUS_VOO.TIPO_STATUS IS 'Tipo do status (PARTIDA ou CHEGADA)';
COMMENT ON COLUMN STATUS_VOO.DESCRICAO IS 'Descrição do status (ex: Programado, Embarcando, Taxiando)';

CREATE TABLE STATUS_VOO (
    ID_STATUS NUMBER PRIMARY KEY,
    TIPO_STATUS VARCHAR2(10) CHECK (TIPO_STATUS IN ('PARTIDA', 'CHEGADA')),
    DESCRICAO VARCHAR2(50) NOT NULL,
    CONSTRAINT UK_STATUS UNIQUE (TIPO_STATUS, DESCRICAO)
);


-- VOO: Tabela principal de cadastro de voos
COMMENT ON TABLE VOO IS 'Registro completo de todos os voos operados pelo sistema';

COMMENT ON COLUMN VOO.ID_VOO IS 'Identificador único do voo (PK)';
COMMENT ON COLUMN VOO.NUMERO_VOO IS 'Número do voo conforme definido pela empresa (ex: LA 1234)';
COMMENT ON COLUMN VOO.ID_EMPRESA IS 'Empresa aérea operadora do voo (FK para EMPRESA_AEREA)';
COMMENT ON COLUMN VOO.CODIGO_DI IS 'Código de identificação do voo (DI)';
COMMENT ON COLUMN VOO.CODIGO_TIPO_LINHA IS 'Tipo de linha aérea (Doméstica, Internacional, etc)';
COMMENT ON COLUMN VOO.MODELO_EQUIPAMENTO IS 'Modelo da aeronave utilizada no voo';
COMMENT ON COLUMN VOO.NUMERO_DE_ASSENTOS IS 'Capacidade total de passageiros da aeronave';
COMMENT ON COLUMN VOO.ID_AEROPORTO_ORI IS 'Aeroporto de origem do voo (FK para AEROPORTO)';
COMMENT ON COLUMN VOO.ID_AEROPORTO_DES IS 'Aeroporto de destino do voo (FK para AEROPORTO)';
COMMENT ON COLUMN VOO.ID_STATUS_PARTIDA IS 'Status atual da partida (FK para STATUS_VOO)';
COMMENT ON COLUMN VOO.ID_STATUS_CHEGADA IS 'Status atual da chegada (FK para STATUS_VOO)';

CREATE TABLE VOO (
    ID_VOO NUMBER PRIMARY KEY,
    NUMERO_VOO VARCHAR2(10),
    ID_EMPRESA NUMBER,
    CODIGO_DI VARCHAR2(10),
    CODIGO_TIPO_LINHA VARCHAR2(10),
    MODELO_EQUIPAMENTO VARCHAR2(50),
    NUMERO_DE_ASSENTOS NUMBER,
    ID_AEROPORTO_ORI NUMBER,
    ID_AEROPORTO_DES NUMBER,
    ID_STATUS_PARTIDA NUMBER,
    ID_STATUS_CHEGADA NUMBER,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA_AEREA(ID_EMPRESA),
    FOREIGN KEY (ID_AEROPORTO_ORI) REFERENCES AEROPORTO(ID_AEROPORTO),
    FOREIGN KEY (ID_AEROPORTO_DES) REFERENCES AEROPORTO(ID_AEROPORTO),
    FOREIGN KEY (ID_STATUS_PARTIDA) REFERENCES STATUS_VOO(ID_STATUS),
    FOREIGN KEY (ID_STATUS_CHEGADA) REFERENCES STATUS_VOO(ID_STATUS)
);


-- DATAS_VOO: Tabela de datas e horários dos voos
COMMENT ON TABLE DATAS_VOO IS 'Registra os horários previstos e reais de partida/chegada dos voos';

COMMENT ON COLUMN DATAS_VOO.ID_DATA IS 'Identificador único do registro de data/horário (PK)';
COMMENT ON COLUMN DATAS_VOO.ID_VOO IS 'Referência ao voo relacionado (FK para VOO)';
COMMENT ON COLUMN DATAS_VOO.PARTIDA_PREVISTA IS 'Data e hora previstas para partida';
COMMENT ON COLUMN DATAS_VOO.PARTIDA_REAL IS 'Data e hora reais da partida';
COMMENT ON COLUMN DATAS_VOO.CHEGADA_PREVISTA IS 'Data e hora previstas para chegada';
COMMENT ON COLUMN DATAS_VOO.CHEGADA_REAL IS 'Data e hora reais da chegada';
COMMENT ON COLUMN DATAS_VOO.REFERENCIA IS 'Data de referência para agrupamento de voos';

CREATE TABLE DATAS_VOO (
    ID_DATA NUMBER PRIMARY KEY,
    ID_VOO NUMBER,
    PARTIDA_PREVISTA TIMESTAMP,
    PARTIDA_REAL TIMESTAMP,
    CHEGADA_PREVISTA TIMESTAMP,
    CHEGADA_REAL TIMESTAMP,
    REFERENCIA DATE,
    FOREIGN KEY (ID_VOO) REFERENCES VOO(ID_VOO)
);


--TRIGGERS
CREATE OR REPLACE TRIGGER TRG_COMPANHIA_AI
BEFORE INSERT ON COMPANHIA_AEREA
FOR EACH ROW
BEGIN
    :NEW.ID_COMPANHIA := SEQ_COMPANHIA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMPRESA_ID
BEFORE INSERT ON EMPRESA_AEREA
FOR EACH ROW
BEGIN
    :NEW.ID_EMPRESA := SEQ_EMPRESA.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_AEROPORTO_AI
BEFORE INSERT ON AEROPORTO
FOR EACH ROW
BEGIN
   :NEW.ID_AEROPORTO := SEQ_AEROPORTO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DATAS_VOO_AI
BEFORE INSERT ON DATAS_VOO
FOR EACH ROW
BEGIN
    :NEW.ID_DATA := SEQ_DATAS_VOO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_VOO_AI
BEFORE INSERT ON VOO
FOR EACH ROW
BEGIN
    :NEW.ID_VOO := SEQ_VOO.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_STATUS_AI
BEFORE INSERT ON STATUS_VOO
FOR EACH ROW
BEGIN
    :NEW.ID_STATUS := SEQ_STATUS.NEXTVAL;
END;
/

--INSERTS
INSERT INTO Companhia_Aerea(nome)
SELECT DISTINCT EMPRESA 
FROM vra_11;


INSERT INTO Empresa_Aerea (Sigla_ICAO, id_companhia)
SELECT v.ICAO, c.id_companhia
FROM (
    SELECT ICAO, empresa, 
           ROW_NUMBER() OVER (PARTITION BY ICAO ORDER BY empresa) AS rn
    FROM vra_11 
    WHERE ICAO IS NOT NULL
) v
JOIN Companhia_Aerea c ON v.empresa = c.Nome
WHERE v.rn = 1
AND NOT EXISTS (
    SELECT 1 FROM Empresa_Aerea ea 
    WHERE ea.Sigla_ICAO = v.ICAO
);

INSERT INTO AEROPORTO (SIGLA_AER, NOME_AEROPORTO, ID_EMP_AER)
SELECT 
    v.AER_ORIGEM,
    v.DESC_AER_ORIG,  
    e.id_empresa
FROM 
    (SELECT DISTINCT AER_ORIGEM, DESC_AER_ORIG, ICAO FROM vra_11) v
    JOIN Empresa_Aerea e ON v.ICAO = e.Sigla_ICAO
UNION
SELECT 
    v.AER_DEST,
    v.DESC_AER_DEST,  
    e.id_empresa
FROM 
    (SELECT DISTINCT AER_DEST, DESC_AER_DEST, ICAO FROM vra_11) v
    JOIN Empresa_Aerea e ON v.ICAO = e.Sigla_ICAO;
        
INSERT INTO STATUS_VOO (ID_STATUS, TIPO_STATUS, DESCRICAO)
SELECT 
    seq_status_part.NEXTVAL,
    'PARTIDA',
    v.SITUA_PART
FROM 
    (SELECT DISTINCT SITUA_PART FROM vra_11 WHERE SITUA_PART IS NOT NULL) v;

INSERT INTO STATUS_VOO (ID_STATUS, TIPO_STATUS, DESCRICAO)
SELECT 
    seq_status_cheg.NEXTVAL,
    'CHEGADA',
    v.SITUA_CHEG
FROM 
    (SELECT DISTINCT SITUA_CHEG FROM vra_11 WHERE SITUA_CHEG IS NOT NULL) v;
    STATUS_VOO_CHE;

INSERT INTO VOO (
    NUMERO_VOO,
    ID_EMPRESA,
    CODIGO_DI,
    CODIGO_TIPO_LINHA,
    MODELO_EQUIPAMENTO,
    NUMERO_DE_ASSENTOS,
    ID_AEROPORTO_ORI,
    ID_AEROPORTO_DES,
    ID_STATUS_PARTIDA,
    ID_STATUS_CHEGADA
)
WITH 
vra_distinct AS (
    SELECT DISTINCT 
        NÚM,
        ICAO,
        DI,
        LINHA,
        MODELO,
        ASSENTOS,
        AER_ORIGEM,
        AER_DEST,
        SITUA_PART,
        SITUA_CHEG
    FROM VRA_11
),
empresa_unique AS (
    SELECT 
        SIGLA_ICAO,
        MIN(ID_EMPRESA) AS ID_EMPRESA 
    FROM EMPRESA_AEREA
    GROUP BY SIGLA_ICAO
),
aeroporto_unique AS (
    SELECT 
        SIGLA_AER,
        MIN(ID_AEROPORTO) AS ID_AEROPORTO
    FROM AEROPORTO
    GROUP BY SIGLA_AER
)
SELECT 
    v.NÚM,
    eu.ID_EMPRESA,
    v.DI,
    COALESCE(v.LINHA, 'N/I'),
    COALESCE(v.MODELO, 'MODELO NÃO INFORMADO'),
    COALESCE(v.ASSENTOS, 0),
    (SELECT ID_AEROPORTO FROM aeroporto_unique WHERE SIGLA_AER = v.AER_ORIGEM),
    (SELECT ID_AEROPORTO FROM aeroporto_unique WHERE SIGLA_AER = v.AER_DEST),
    (SELECT MIN(ID_STATUS) FROM STATUS_VOO WHERE TIPO_STATUS = 'PARTIDA' AND DESCRICAO = v.SITUA_PART),
    COALESCE(
        (SELECT MIN(ID_STATUS) FROM STATUS_VOO WHERE TIPO_STATUS = 'CHEGADA' AND DESCRICAO = v.SITUA_CHEG),
        (SELECT MIN(ID_STATUS) FROM STATUS_VOO WHERE TIPO_STATUS = 'CHEGADA' AND DESCRICAO = 'STATUS NÃO INFORMADO')
    )
FROM vra_distinct v
LEFT JOIN empresa_unique eu ON eu.SIGLA_ICAO = v.ICAO;


INSERT INTO DATAS_VOO (
    PARTIDA_PREVISTA,
    PARTIDA_REAL,
    CHEGADA_PREVISTA,
    CHEGADA_REAL,
    REFERENCIA,
    ID_VOO
)
SELECT 
    v.PART_PREV,
    v.PART_REAL,
    v.CHEG_PREV,
    v.CHEG_REAL,
    v.REFERÊNCIA,
    vo.ID_VOO
FROM (
    SELECT DISTINCT
        NÚM,
        PART_PREV,
        PART_REAL,
        CHEG_PREV,
        CHEG_REAL,
        REFERÊNCIA
    FROM VRA_11
) v
JOIN VOO vo ON v.NÚM = vo.NUMERO_VOO;

--Consultas Estratégicas
--Rotas mais populares (maior número de voos)
SELECT 
    ao.SIGLA_AER AS ORIGEM,
    ao.NOME_AEROPORTO AS NOME_ORIGEM,
    ad.SIGLA_AER AS DESTINO,
    ad.NOME_AEROPORTO AS NOME_DESTINO,
    COUNT(*) AS TOTAL_VOOS
FROM 
    VOO v
JOIN AEROPORTO ao ON v.ID_AEROPORTO_ORI = ao.ID_AEROPORTO
JOIN AEROPORTO ad ON v.ID_AEROPORTO_DES = ad.ID_AEROPORTO
GROUP BY 
    ao.SIGLA_AER, ao.NOME_AEROPORTO, ad.SIGLA_AER, ad.NOME_AEROPORTO
ORDER BY 
    TOTAL_VOOS DESC
FETCH FIRST 10 ROWS ONLY;

--Aeroportos com maior número de voos de saída
SELECT 
    a.SIGLA_AER AS AEROPORTO,
    a.NOME_AEROPORTO AS NOME_AEROPORTO,
    COUNT(*) AS TOTAL_VOOS_SAIDA
FROM 
    VOO v
JOIN AEROPORTO a ON v.ID_AEROPORTO_ORI = a.ID_AEROPORTO
GROUP BY 
    a.SIGLA_AER, a.NOME_AEROPORTO
ORDER BY 
    TOTAL_VOOS_SAIDA DESC
FETCH FIRST 10 ROWS ONLY;

--Modelos de aeronaves mais utilizados
SELECT 
    MODELO_EQUIPAMENTO,
    COUNT(*) AS TOTAL_VOOS
FROM 
    VOO
WHERE 
    MODELO_EQUIPAMENTO != 'MODELO NÃO INFORMADO'
GROUP BY 
    MODELO_EQUIPAMENTO
ORDER BY 
    TOTAL_VOOS DESC;

--Voos por dia da semana   
SELECT 
    TO_CHAR(dv.REFERENCIA, 'DAY') AS DIA_SEMANA,
    COUNT(*) AS TOTAL_VOOS
FROM 
    DATAS_VOO dv
GROUP BY 
    TO_CHAR(dv.REFERENCIA, 'DAY'), TO_CHAR(dv.REFERENCIA, 'D')
ORDER BY 
    TO_CHAR(dv.REFERENCIA, 'D');
    
--Companhias aéreas com maior diversidade de rotas
SELECT 
    c.NOME AS COMPANHIA_AEREA,
    COUNT(DISTINCT v.ID_AEROPORTO_ORI || '-' || v.ID_AEROPORTO_DES) AS ROTAS_DISTINTAS
FROM 
    VOO v
JOIN EMPRESA_AEREA ea ON v.ID_EMPRESA = ea.ID_EMPRESA
JOIN COMPANHIA_AEREA c ON ea.ID_COMPANHIA = c.ID_COMPANHIA
GROUP BY 
    c.NOME
ORDER BY 
    ROTAS_DISTINTAS DESC;
    
--Companhias com Melhor Pontualidade (considerando apenas voos pontuais)
SELECT 
    c.NOME AS COMPANHIA_AEREA,
    COUNT(*) AS TOTAL_VOOS,
    SUM(CASE WHEN sv.DESCRICAO = 'Pontual' AND sv.TIPO_STATUS = 'PARTIDA' THEN 1 ELSE 0 END) AS VOOS_PONTUAIS,
    ROUND(SUM(CASE WHEN sv.DESCRICAO = 'Pontual' AND sv.TIPO_STATUS = 'PARTIDA' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS PERCENTUAL_PONTUALIDADE
FROM 
    VOO v
JOIN EMPRESA_AEREA ea ON v.ID_EMPRESA = ea.ID_EMPRESA
JOIN COMPANHIA_AEREA c ON ea.ID_COMPANHIA = c.ID_COMPANHIA
JOIN STATUS_VOO sv ON v.ID_STATUS_PARTIDA = sv.ID_STATUS
GROUP BY 
    c.NOME
ORDER BY 
    PERCENTUAL_PONTUALIDADE DESC;
    
    
    
-----HISTÓRICO-----    
-----TABELA-----

CREATE TABLE H_VOO (
    H_VOO_ID NUMBER,
    H_VOO_NUMERO VARCHAR2(10),
    H_VOO_EMP_ID NUMBER,
    H_VOO_COD_DI VARCHAR2(10),
    H_VOO_COD_TIPO_LINHA VARCHAR2(10),
    H_VOO_MOD_EQUIP VARCHAR2(50),
    H_VOO_NUM_ASSENTOS NUMBER,
    H_VOO_AER_ORI_ID NUMBER,
    H_VOO_AER_DES_ID NUMBER,
    H_VOO_STS_PART_ID NUMBER,
    H_VOO_STS_CHEG_ID NUMBER,
    H_VOO_DATA_ALTERACAO DATE,
    CONSTRAINT PK_H_VOO PRIMARY KEY (H_VOO_ID, H_VOO_DATA_ALTERACAO)
);

-----TRIGGER-----

CREATE TRIGGER TG_HVOO
BEFORE UPDATE OR DELETE
ON VOO
FOR EACH ROW
BEGIN
    INSERT INTO H_VOO VALUES (
        :OLD.VOO_ID, 
        :OLD.VOO_NUMERO, 
        :OLD.VOO_EMP_ID, 
        :OLD.VOO_COD_DI, 
        :OLD.VOO_COD_TIPO_LINHA,
        :OLD.VOO_MOD_EQUIP, 
        :OLD.VOO_NUM_ASSENTOS, 
        :OLD.VOO_AER_ORI_ID, 
        :OLD.VOO_AER_DES_ID,
        :OLD.VOO_STS_PART_ID, 
        :OLD.VOO_STS_CHEG_ID, 
        SYSDATE
    );
END;
/
-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------

-----TABELA-----

CREATE TABLE H_DATAS_VOO (
    H_DTV_ID NUMBER,
    H_DTV_VOO_ID NUMBER,
    H_DTV_PART_PREV TIMESTAMP,
    H_DTV_PART_REAL TIMESTAMP,
    H_DTV_CHEG_PREV TIMESTAMP,
    H_DTV_CHEG_REAL TIMESTAMP,
    H_DTV_REF DATE,
    H_DTV_DATA_ALTERACAO DATE,
    CONSTRAINT PK_H_DATAS_VOO PRIMARY KEY (H_DTV_ID, H_DTV_DATA_ALTERACAO)
);


-----TRIGGER-----

CREATE TRIGGER TG_HDTV
BEFORE UPDATE OR DELETE
ON DATAS_VOO
FOR EACH ROW
BEGIN
    INSERT INTO H_DATAS_VOO VALUES (
        :OLD.DTV_ID,
        :OLD.DTV_VOO_ID,
        :OLD.DTV_PART_PREV,
        :OLD.DTV_PART_REAL,
        :OLD.DTV_CHEG_PREV,
        :OLD.DTV_CHEG_REAL,
        :OLD.DTV_REF,
        SYSDATE
    );
END;
/