ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER STAGE IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE MATERIALIZED VIEW TO STAGE;
GRANT CREATE ANY TABLE TO STAGE;
GRANT SELECT ANY TABLE TO STAGE;
GRANT QUERY REWRITE TO STAGE;
GRANT GLOBAL QUERY REWRITE TO STAGE;
GRANT SELECT ON SYSTEM.VOO TO STAGE;
GRANT SELECT ON SYSTEM.DATAS_VOO TO STAGE;
GRANT SELECT ON SYSTEM.COMPANHIA_AEREA TO STAGE;
GRANT SELECT ON SYSTEM.EMPRESA_AEREA TO STAGE;
GRANT SELECT ON SYSTEM.AEROPORTO TO STAGE;
GRANT SELECT ON SYSTEM.STATUS_VOO TO STAGE;
GRANT CREATE MATERIALIZED VIEW TO STAGE;
GRANT QUERY REWRITE TO STAGE;
GRANT CONNECT, RESOURCE TO STAGE;
ALTER SESSION SET CURRENT_SCHEMA = STAGE;

--------------------------------------------------------
--  DDL for Materialized View STAGE_VOO_ANALYTICS
--------------------------------------------------------
CREATE MATERIALIZED VIEW STAGE_VOO_ANALYTICS
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    v.VOO_ID,
    v.VOO_NUMERO,
    ea.EMP_SIGLA_ICAO AS SIGLA_EMPRESA,
    c.COM_NOME AS COMPANHIA_AEREA,
    v.VOO_MOD_EQUIP AS MODELO_AERONAVE,
    ao.AER_SIGLA AS AEROPORTO_ORIGEM,
    ao.AER_NOME AS NOME_AEROPORTO_ORIGEM,
    ad.AER_SIGLA AS AEROPORTO_DESTINO,
    ad.AER_NOME AS NOME_AEROPORTO_DESTINO,
    sp.STS_DESC AS STATUS_PARTIDA,
    sc.STS_DESC AS STATUS_CHEGADA,
    dv.DTV_PART_PREV AS PARTIDA_PREVISTA,
    dv.DTV_PART_REAL AS PARTIDA_REAL,
    dv.DTV_CHEG_PREV AS CHEGADA_PREVISTA,
    dv.DTV_CHEG_REAL AS CHEGADA_REAL,
    dv.DTV_REF AS DATA_REFERENCIA,
    CASE 
        WHEN dv.DTV_PART_REAL IS NULL OR dv.DTV_PART_PREV IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 24 * 60 + 
             EXTRACT(HOUR FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 60 +
             EXTRACT(MINUTE FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV))
    END AS ATRASO_PARTIDA_MINUTOS,
    CASE 
        WHEN dv.DTV_CHEG_REAL IS NULL OR dv.DTV_CHEG_PREV IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 24 * 60 + 
             EXTRACT(HOUR FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 60 +
             EXTRACT(MINUTE FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV))
    END AS ATRASO_CHEGADA_MINUTOS,
    NULL AS DATA_ALTERACAO,
    'ATUAL' AS TIPO_REGISTRO
FROM 
    SYSTEM.VOO v
JOIN SYSTEM.EMPRESA_AEREA ea ON v.VOO_EMP_ID = ea.EMP_ID
JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
JOIN SYSTEM.AEROPORTO ao ON v.VOO_AER_ORI_ID = ao.AER_ID
JOIN SYSTEM.AEROPORTO ad ON v.VOO_AER_DES_ID = ad.AER_ID
JOIN SYSTEM.STATUS_VOO sp ON v.VOO_STS_PART_ID = sp.STS_ID
JOIN SYSTEM.STATUS_VOO sc ON v.VOO_STS_CHEG_ID = sc.STS_ID
LEFT JOIN SYSTEM.DATAS_VOO dv ON v.VOO_ID = dv.DTV_VOO_ID

UNION ALL

SELECT 
    hv.H_VOO_ID AS VOO_ID,
    hv.H_VOO_NUMERO AS VOO_NUMERO,
    ea.EMP_SIGLA_ICAO AS SIGLA_EMPRESA,
    c.COM_NOME AS COMPANHIA_AEREA,
    hv.H_VOO_MOD_EQUIP AS MODELO_AERONAVE,
    ao.AER_SIGLA AS AEROPORTO_ORIGEM,
    ao.AER_NOME AS NOME_AEROPORTO_ORIGEM,
    ad.AER_SIGLA AS AEROPORTO_DESTINO,
    ad.AER_NOME AS NOME_AEROPORTO_DESTINO,
    sp.STS_DESC AS STATUS_PARTIDA,
    sc.STS_DESC AS STATUS_CHEGADA,
    hdv.H_DTV_PART_PREV AS PARTIDA_PREVISTA,
    hdv.H_DTV_PART_REAL AS PARTIDA_REAL,
    hdv.H_DTV_CHEG_PREV AS CHEGADA_PREVISTA,
    hdv.H_DTV_CHEG_REAL AS CHEGADA_REAL,
    hdv.H_DTV_REF AS DATA_REFERENCIA,
    CASE 
        WHEN hdv.H_DTV_PART_REAL IS NULL OR hdv.H_DTV_PART_PREV IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 24 * 60 + 
             EXTRACT(HOUR FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 60 +
             EXTRACT(MINUTE FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV))
    END AS ATRASO_PARTIDA_MINUTOS,
    CASE 
        WHEN hdv.H_DTV_CHEG_REAL IS NULL OR hdv.H_DTV_CHEG_PREV IS NULL THEN NULL
        ELSE EXTRACT(DAY FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 24 * 60 + 
             EXTRACT(HOUR FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 60 +
             EXTRACT(MINUTE FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV))
    END AS ATRASO_CHEGADA_MINUTOS,
    hv.H_VOO_DATA_ALTERACAO AS DATA_ALTERACAO,
    'HISTORICO' AS TIPO_REGISTRO
FROM 
    SYSTEM.H_VOO hv
JOIN SYSTEM.EMPRESA_AEREA ea ON hv.H_VOO_EMP_ID = ea.EMP_ID
JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
JOIN SYSTEM.AEROPORTO ao ON hv.H_VOO_AER_ORI_ID = ao.AER_ID
JOIN SYSTEM.AEROPORTO ad ON hv.H_VOO_AER_DES_ID = ad.AER_ID
JOIN SYSTEM.STATUS_VOO sp ON hv.H_VOO_STS_PART_ID = sp.STS_ID
JOIN SYSTEM.STATUS_VOO sc ON hv.H_VOO_STS_CHEG_ID = sc.STS_ID
LEFT JOIN SYSTEM.H_DATAS_VOO hdv ON hv.H_VOO_ID = hdv.H_DTV_VOO_ID 
    AND hv.H_VOO_DATA_ALTERACAO = hdv.H_DTV_DATA_ALTERACAO;

COMMENT ON MATERIALIZED VIEW STAGE_VOO_ANALYTICS IS 'Visão consolidada para análise de voos no Power BI';

--------------------------------------------------------
--  DDL for Materialized View STAGE_ROTAS_POPULARES
--------------------------------------------------------
CREATE MATERIALIZED VIEW STAGE_ROTAS_POPULARES
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT 
    ao.AER_SIGLA AS ORIGEM,
    ao.AER_NOME AS NOME_ORIGEM,
    ad.AER_SIGLA AS DESTINO,
    ad.AER_NOME AS NOME_DESTINO,
    c.COM_NOME AS COMPANHIA_AEREA,
    COUNT(*) AS TOTAL_VOOS,
    ROUND(AVG(
        CASE 
            WHEN dv.DTV_PART_REAL IS NOT NULL AND dv.DTV_PART_PREV IS NOT NULL 
            THEN EXTRACT(DAY FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 1440 +  
                 EXTRACT(HOUR FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 60 +  
                 EXTRACT(MINUTE FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV))    
            ELSE NULL 
        END
    ), 0) AS MEDIA_ATRASO_PARTIDA_MIN,
    ROUND(AVG(
        CASE 
            WHEN dv.DTV_CHEG_REAL IS NOT NULL AND dv.DTV_CHEG_PREV IS NOT NULL 
            THEN EXTRACT(DAY FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 1440 +  
                 EXTRACT(HOUR FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 60 +   
                 EXTRACT(MINUTE FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV))      
            ELSE NULL 
        END
    ), 0) AS MEDIA_ATRASO_CHEGADA_MIN,
    COUNT(DISTINCT v.VOO_MOD_EQUIP) AS MODELOS_AERONAVES_DISTINTOS,
    'ATUAL' AS TIPO_REGISTRO
FROM 
    SYSTEM.VOO v
JOIN SYSTEM.EMPRESA_AEREA ea ON v.VOO_EMP_ID = ea.EMP_ID
JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
JOIN SYSTEM.AEROPORTO ao ON v.VOO_AER_ORI_ID = ao.AER_ID
JOIN SYSTEM.AEROPORTO ad ON v.VOO_AER_DES_ID = ad.AER_ID
LEFT JOIN SYSTEM.DATAS_VOO dv ON v.VOO_ID = dv.DTV_VOO_ID
GROUP BY 
    ao.AER_SIGLA, ao.AER_NOME, ad.AER_SIGLA, ad.AER_NOME, c.COM_NOME

UNION ALL

SELECT 
    ao.AER_SIGLA AS ORIGEM,
    ao.AER_NOME AS NOME_ORIGEM,
    ad.AER_SIGLA AS DESTINO,
    ad.AER_NOME AS NOME_DESTINO,
    c.COM_NOME AS COMPANHIA_AEREA,
    COUNT(*) AS TOTAL_VOOS,
    ROUND(AVG(
        CASE 
            WHEN hdv.H_DTV_PART_REAL IS NOT NULL AND hdv.H_DTV_PART_PREV IS NOT NULL 
            THEN EXTRACT(DAY FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 1440 +  
                 EXTRACT(HOUR FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 60 +  
                 EXTRACT(MINUTE FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV))    
            ELSE NULL 
        END
    ), 0) AS MEDIA_ATRASO_PARTIDA_MIN,
    ROUND(AVG(
        CASE 
            WHEN hdv.H_DTV_CHEG_REAL IS NOT NULL AND hdv.H_DTV_CHEG_PREV IS NOT NULL 
            THEN EXTRACT(DAY FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 1440 +  
                 EXTRACT(HOUR FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 60 +   
                 EXTRACT(MINUTE FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV))      
            ELSE NULL 
        END
    ), 0) AS MEDIA_ATRASO_CHEGADA_MIN,
    COUNT(DISTINCT hv.H_VOO_MOD_EQUIP) AS MODELOS_AERONAVES_DISTINTOS,
    'HISTORICO' AS TIPO_REGISTRO
FROM 
    SYSTEM.H_VOO hv
JOIN SYSTEM.EMPRESA_AEREA ea ON hv.H_VOO_EMP_ID = ea.EMP_ID
JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
JOIN SYSTEM.AEROPORTO ao ON hv.H_VOO_AER_ORI_ID = ao.AER_ID
JOIN SYSTEM.AEROPORTO ad ON hv.H_VOO_AER_DES_ID = ad.AER_ID
LEFT JOIN SYSTEM.H_DATAS_VOO hdv ON hv.H_VOO_ID = hdv.H_DTV_VOO_ID 
    AND hv.H_VOO_DATA_ALTERACAO = hdv.H_DTV_DATA_ALTERACAO
GROUP BY 
    ao.AER_SIGLA, ao.AER_NOME, ad.AER_SIGLA, ad.AER_NOME, c.COM_NOME;

COMMENT ON MATERIALIZED VIEW STAGE_ROTAS_POPULARES IS 'Análise de rotas mais populares para Power BI';

--------------------------------------------------------
--  DDL for Materialized View STAGE_PONTUALIDADE_COMPANHIAS
--------------------------------------------------------
CREATE MATERIALIZED VIEW STAGE_PONTUALIDADE_COMPANHIAS
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
WITH dados_pontualidade AS (
  SELECT 
    c.COM_NOME,
    EXTRACT(DAY FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 24 * 60 +
    EXTRACT(HOUR FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) * 60 +
    EXTRACT(MINUTE FROM (dv.DTV_PART_REAL - dv.DTV_PART_PREV)) AS minutos_atraso_partida,
    EXTRACT(DAY FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 24 * 60 +
    EXTRACT(HOUR FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) * 60 +
    EXTRACT(MINUTE FROM (dv.DTV_CHEG_REAL - dv.DTV_CHEG_PREV)) AS minutos_atraso_chegada,
    'ATUAL' AS TIPO_REGISTRO
  FROM SYSTEM.VOO v
  JOIN SYSTEM.EMPRESA_AEREA ea ON v.VOO_EMP_ID = ea.EMP_ID
  JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
  JOIN SYSTEM.DATAS_VOO dv ON v.VOO_ID = dv.DTV_VOO_ID
  
  UNION ALL
  
  SELECT 
    c.COM_NOME,
    EXTRACT(DAY FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 24 * 60 +
    EXTRACT(HOUR FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) * 60 +
    EXTRACT(MINUTE FROM (hdv.H_DTV_PART_REAL - hdv.H_DTV_PART_PREV)) AS minutos_atraso_partida,
    EXTRACT(DAY FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 24 * 60 +
    EXTRACT(HOUR FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) * 60 +
    EXTRACT(MINUTE FROM (hdv.H_DTV_CHEG_REAL - hdv.H_DTV_CHEG_PREV)) AS minutos_atraso_chegada,
    'HISTORICO' AS TIPO_REGISTRO
  FROM SYSTEM.H_VOO hv
  JOIN SYSTEM.EMPRESA_AEREA ea ON hv.H_VOO_EMP_ID = ea.EMP_ID
  JOIN SYSTEM.COMPANHIA_AEREA c ON ea.EMP_COM_ID = c.COM_ID
  JOIN SYSTEM.H_DATAS_VOO hdv ON hv.H_VOO_ID = hdv.H_DTV_VOO_ID 
    AND hv.H_VOO_DATA_ALTERACAO = hdv.H_DTV_DATA_ALTERACAO
)
SELECT 
  COM_NOME AS COMPANHIA_AEREA,
  COUNT(*) AS TOTAL_VOOS,
  SUM(CASE WHEN minutos_atraso_partida <= 15 THEN 1 ELSE 0 END) AS VOOS_PONTUAIS_PARTIDA,
  ROUND(SUM(CASE WHEN minutos_atraso_partida <= 15 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100, 2) AS PERCENTUAL_PONTUALIDADE_PARTIDA,
  SUM(CASE WHEN minutos_atraso_chegada <= 15 THEN 1 ELSE 0 END) AS VOOS_PONTUAIS_CHEGADA,
  ROUND(SUM(CASE WHEN minutos_atraso_chegada <= 15 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100, 2) AS PERCENTUAL_PONTUALIDADE_CHEGADA,
  TIPO_REGISTRO
FROM dados_pontualidade
GROUP BY COM_NOME, TIPO_REGISTRO;

COMMENT ON MATERIALIZED VIEW STAGE_PONTUALIDADE_COMPANHIAS IS 'Métricas de pontualidade por companhia aérea para Power BI';

--------------------------------------------------------
-- Procedimento para refresh nas views
--------------------------------------------------------
BEGIN
   DBMS_MVIEW.REFRESH('stage_voo_analytics', method => 'C', atomic_refresh => FALSE);
   DBMS_MVIEW.REFRESH('stage_rotas_populares', method => 'C', atomic_refresh => FALSE);
   DBMS_MVIEW.REFRESH('stage_pontualidade_companhias', method => 'C', atomic_refresh => FALSE);
END;
/